name: exercise

on:
  workflow_dispatch:
    inputs:
      skip_push:
        type: boolean
        description: 'Skip pushing to DockerHub'
        required: false
        default: false

jobs:
  lint-and-test:
    name: Linting and testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Run Lint
        id: npm-lint
        run: npm run lint

      - name: Run Test
        id: npm-ci-test
        run: npm run test

  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/github-action-school .

      - name: Push to Dockerhub
        if: ${{ inputs.skip_push == 'false' }}
        run: docker push ${{ secrets.DOCKER_USERNAME }}/github-action-school
